version: "3"

# Set env file to be accessible inside docker-compose
env_file: ./linuxfest-backend/.env.dev

services:
  nginx:
    container_name: nginx
    ports:
      - "80:80"
    build:
      context: ./nginx
    networks:
      - nginx-net
    depends_on:
      - node-app

  node-app:
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        parallelism: 2
        delay: 15s
    build:
      context: ./linuxfest-backend/
      args:
        NODE_ENV: production
    volumes:
      - upload-files:/app/uploads
    environment:
      - NODE_ENV=production
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - PWD=/app
    env_file:
      - ./linuxfest-backend/.env.dev
    networks:
      - api-net
      - nginx-net
    depends_on:
      - mongo
    command: node index.js

  mongo:
    image: mongo
    container_name: mongodb
    volumes:
      - mongo-db:/data/db
    networks:
      - api-net
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

volumes:
  upload-files:
  mongo-db:

networks:
  api-net: {}
  nginx-net: {}
